# Generated by Django 3.2.5 on 2021-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdf',
            field=models.FileField(default='', upload_to='resume/'),
        ),
    ]
