# Generated by Django 3.2.5 on 2021-10-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobWork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='5 LPA', max_length=100),
        ),
    ]
