# Generated by Django 3.2.5 on 2021-10-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobWork', '0002_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=100),
        ),
    ]
