# Generated by Django 3.2.5 on 2021-12-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobWork', '0003_alter_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='filled',
        ),
        migrations.RemoveField(
            model_name='job',
            name='website',
        ),
    ]
